language: python
python:
  - "3.6"
env:
  - DJANGO_VERSION=2.0
install:
  - pip install Django==$DJANGO_VERSION
  - pip install tox-travis
  - pip install -q -r requirements.txt
  - pip install coverage
  - pip install codecov
script:
after_success:
  - codecov